# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZBfQttxeGW8ICOhFhLxa4sW8XWuXogb
"""

# [1] 폰트 + 라이브러리
!apt-get -qq -y install fonts-nanum

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns

font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
fm.fontManager.addfont(font_path)
plt.rcParams["font.family"] = "NanumGothic"
plt.rcParams["axes.unicode_minus"] = False

# [2] 엑셀 불러오기 + 전처리
excel_path = "/content/AdventureWorks Sales (2).xlsx"

sales_order_df = pd.read_excel(excel_path, sheet_name="Sales Order_data")
sales_df       = pd.read_excel(excel_path, sheet_name="Sales_data")
customer_df    = pd.read_excel(excel_path, sheet_name="Customer_data")
date_df        = pd.read_excel(excel_path, sheet_name="Date_data")

# merge → clean → adventure_df 만들기 (아까 준 코드 그대로)

# [1] 환경 세팅 & 한글 폰트
!apt-get -qq -y install fonts-nanum

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns

# 나눔고딕 경로
font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
fm.fontManager.addfont(font_path)

plt.rcParams["font.family"] = "NanumGothic"
plt.rcParams["axes.unicode_minus"] = False

print("✅ 나눔고딕 폰트 적용 완료!")

# [2] 엑셀 불러오기 & 시트 목록 확인

excel_path = "/content/AdventureWorks Sales (2).xlsx"  # 🔁 여기 파일 이름 네 거랑 맞춰줘!

xls = pd.ExcelFile(excel_path)
print("📄 시트 목록:", xls.sheet_names)

# [3] 각 시트별 DataFrame 만들기

sales_order_df = pd.read_excel(excel_path, sheet_name="Sales Order_data")
sales_df       = pd.read_excel(excel_path, sheet_name="Sales_data")
customer_df    = pd.read_excel(excel_path, sheet_name="Customer_data")
date_df        = pd.read_excel(excel_path, sheet_name="Date_data")

print("✅ Sales_data:", sales_df.shape)
print("✅ Sales Order_data:", sales_order_df.shape)
print("✅ Customer_data:", customer_df.shape)
print("✅ Date_data:", date_df.shape)

display(sales_df.head())
display(sales_order_df.head())
display(customer_df.head())
display(date_df.head())

# [4-1] Sales_data + Sales Order_data 병합
# 공통 키: SalesOrderLineKey

merged_df = pd.merge(
    sales_df,
    sales_order_df[["SalesOrderLineKey", "Channel", "Sales Order", "Sales Order Line"]],
    on="SalesOrderLineKey",
    how="left"
)

print("🔗 1차 병합:", merged_df.shape)
display(merged_df.head())

# [4-2] Customer_data 붙이기
# 공통 키: CustomerKey

merged_df = pd.merge(
    merged_df,
    customer_df,
    on="CustomerKey",
    how="left"
)

print("🔗 2차 병합 (Customer 포함):", merged_df.shape)
display(merged_df.head())



# [4-3] Date_data 붙이기 (OrderDateKey -> 실제 날짜)

merged_df = pd.merge(
    merged_df,
    date_df[["DateKey", "Date", "MonthKey"]],
    left_on="OrderDateKey",
    right_on="DateKey",
    how="left"
)

print("🔗 3차 병합 (날짜 포함):", merged_df.shape)
display(merged_df[["OrderDateKey", "Date", "MonthKey"]].head())

print("📄 date_df 컬럼명:", date_df.columns.tolist())
print("📄 merged_df 컬럼명:", merged_df.columns.tolist())

# [4-3] Date_data 붙이기 (OrderDateKey -> 실제 날짜)

merged_df = pd.merge(
    merged_df,
    date_df[["DateKey", "Date", "MonthKey"]],
    left_on="OrderDateKey",
    right_on="DateKey",
    how="left"
)

# 👉 y 쪽(이번에 붙인) 날짜/월 컬럼을 정식 이름으로 사용
merged_df = merged_df.rename(columns={
    "Date_y": "Date",
    "MonthKey_y": "MonthKey"
})

# 👉 더 이상 필요 없는 x쪽/키 컬럼은 정리
merged_df = merged_df.drop(columns=[
    "Date_x", "MonthKey_x", "DateKey_x", "DateKey_y"
], errors="ignore")

print("🔗 3차 병합 (날짜 포함):", merged_df.shape)
display(merged_df[["OrderDateKey", "Date", "MonthKey"]].head())

# [4-4] "[Not Applicable]" 고객 제거 + 핵심 컬럼만 정리

clean_df = merged_df[merged_df["Customer"] != "[Not Applicable]"].copy()

adventure_df = clean_df[[
    "SalesOrderLineKey",
    "Sales Order",
    "Channel",
    "CustomerKey",
    "Customer",
    "City",
    "State-Province",
    "Country-Region",
    "OrderDateKey",
    "Date",        # 실제 날짜
    "MonthKey",
    "ProductKey",
    "Order Quantity",
    "Unit Price",
    "Sales Amount"
]].copy()

# 컬럼명 조금 예쁘게
adventure_df = adventure_df.rename(columns={
    "Sales Order": "SalesOrderID",
    "State-Province": "StateProvince",
    "Country-Region": "CountryRegion",
    "Order Quantity": "OrderQuantity",
    "Unit Price": "UnitPrice",
    "Sales Amount": "SalesAmount",
    "Date": "OrderDate"
})

adventure_df.info()
display(adventure_df.head())

# [4-5] 타입 변환 + YearMonth 파생 컬럼 정리

# 0️⃣ 혹시 모를 중복 컬럼 제거
dup_cols = adventure_df.columns[adventure_df.columns.duplicated()].tolist()
print("⚠️ 중복 컬럼:", dup_cols)
adventure_df = adventure_df.loc[:, ~adventure_df.columns.duplicated()]

# 1️⃣ 날짜/숫자형 변환
adventure_df["OrderDate"] = pd.to_datetime(
    adventure_df["OrderDate"], errors="coerce"
)

adventure_df["SalesAmount"] = pd.to_numeric(
    adventure_df["SalesAmount"], errors="coerce"
)

adventure_df["OrderQuantity"] = pd.to_numeric(
    adventure_df["OrderQuantity"], errors="coerce"
).astype("Int64")   # 정수 + 결측 허용

# 2️⃣ 연-월 컬럼
adventure_df["YearMonth"] = adventure_df["OrderDate"].dt.to_period("M").astype(str)

display(adventure_df[["OrderDate", "YearMonth", "SalesAmount"]].head())

# [5-1] 월별 매출 추이

monthly_sales = (
    adventure_df.groupby("YearMonth")["SalesAmount"]
                .sum()
                .reset_index()
)

plt.figure(figsize=(12,5))
sns.lineplot(data=monthly_sales, x="YearMonth", y="SalesAmount", marker="o")
plt.xticks(rotation=45)
plt.title("월별 매출 추이")
plt.xlabel("월")
plt.ylabel("매출액")
plt.tight_layout()
plt.show()

# [5-2] 고객별 총 매출 Top 10

customer_sales = (
    adventure_df.groupby("Customer")["SalesAmount"]
                .sum()
                .sort_values(ascending=False)
                .head(10)
                .reset_index()
)

plt.figure(figsize=(10,5))
sns.barplot(data=customer_sales, x="Customer", y="SalesAmount")
plt.xticks(rotation=45, ha="right")
plt.title("고객별 총 매출 Top 10")
plt.xlabel("고객")
plt.ylabel("총 매출액")
plt.tight_layout()
plt.show()

# [5-3] 채널(Channel)별 매출

channel_sales = (
    adventure_df.groupby("Channel")["SalesAmount"]
                .sum()
                .reset_index()
)

plt.figure(figsize=(8,5))
sns.barplot(data=channel_sales, x="Channel", y="SalesAmount")
plt.title("판매 채널별 매출")
plt.xlabel("채널")
plt.ylabel("총 매출액")
plt.tight_layout()
plt.show()

display(channel_sales)

# [6-1] RFM용 데이터 준비

rfm_df = adventure_df.copy()
rfm_df["OrderDate"] = pd.to_datetime(rfm_df["OrderDate"])

# 기준 날짜: 마지막 주문일 + 1일
snapshot_date = rfm_df["OrderDate"].max() + pd.Timedelta(days=1)
print("📌 기준 날짜(snapshot_date):", snapshot_date)

# [6-2] 고객별 R, F, M 계산

rfm = rfm_df.groupby("Customer").agg(
    Recency=("OrderDate", lambda x: (snapshot_date - x.max()).days),  # 마지막 주문으로부터 며칠 지났는지
    Frequency=("SalesOrderID", "nunique"),                            # 주문 건수
    Monetary=("SalesAmount", "sum")                                   # 총 매출액
)

display(rfm.head())

# [6-3] 점수화 (1~5점) - 분위수 기반
# qcut 중복 문제 방지 위해 rank 사용

# Recency: 작을수록 좋은 고객 → 점수 클수록 좋게 라벨
rfm["R_score"] = pd.qcut(
    rfm["Recency"].rank(method="first"),
    5,
    labels=[5,4,3,2,1]  # 5점: 가장 최근에 구매
)

# Frequency, Monetary: 클수록 좋은 고객
rfm["F_score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1,2,3,4,5]
)

rfm["M_score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1,2,3,4,5]
)

display(rfm.head())

# [6-4] 통합 고객생애가치 점수 (CLV_score)

rfm["CLV_score"] = (
    rfm["R_score"].astype(int) * 0.4 +
    rfm["F_score"].astype(int) * 0.3 +
    rfm["M_score"].astype(int) * 0.3
)

rfm["CLV_score"].describe()

# [7-1] 세그먼트 라벨 함수

def label_segment(score: float) -> str:
    if score >= 4.0:
        return "핵심 우량 고객"
    elif score >= 3.0:
        return "성장 고객"
    elif score >= 2.0:
        return "일반/잠재 고객"
    else:
        return "이탈 위험 고객"

rfm["segment"] = rfm["CLV_score"].apply(label_segment)

rfm["segment"].value_counts()

# [7-2] 세그먼트별 요약 (고객수, 평균 점수, 총 매출)

segment_summary = (
    rfm.groupby("segment")
       .agg(
           고객수=("CLV_score", "count"),
           평균점수=("CLV_score", "mean"),
           총매출=("Monetary", "sum")
       )
       .reset_index()
)

display(segment_summary)

# [7-3] 세그먼트별 총 매출 시각화

plt.figure(figsize=(8,5))
sns.barplot(data=segment_summary, x="segment", y="총매출")
plt.title("고객 세그먼트별 총 매출")
plt.xlabel("세그먼트")
plt.ylabel("총 매출")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

import plotly.express as px

country_sales = (
    adventure_df.groupby("CountryRegion")["SalesAmount"]
                .sum()
                .reset_index()
)

fig = px.choropleth(
    country_sales,
    locations="CountryRegion",      # 국가 이름 컬럼
    locationmode="country names",   # 국가 이름으로 매핑
    color="SalesAmount",
    title="국가별 매출"
)
fig.show()

monthly_sales = (
    adventure_df.groupby("YearMonth")["SalesAmount"]
                .sum()
                .reset_index()
)

plt.figure(figsize=(12,5))
sns.barplot(data=monthly_sales, x="YearMonth", y="SalesAmount")
plt.xticks(rotation=45)
plt.title("월별 매출 추이")
plt.xlabel("월")
plt.ylabel("매출액")
plt.tight_layout()
plt.show()

segment_sales = (
    adventure_df.groupby(["ProductKey", "Channel"])["SalesAmount"]
                .sum()
                .reset_index()
)

fig = px.bar(
    segment_sales,
    x="ProductKey",
    y="SalesAmount",
    color="Channel",
    title="제품 + 채널별 매출 (스택 막대)",
    barmode="stack"
)
fig.show()

